type User{
    uid: String
    fullname: String
    username: String
    password: String
    createdAt: DateTimeISO
    Posts: [Post]
}

type Post {
    id:Int
    title: String
    body: String
    createdAt: DateTimeISO
}

input UserInput{
    fullname: String
    username: String
    password: String
}

union UserOrPostRes = User | Post
union UserResult = User | BadUserInput | UserNotFound | Unauthorized | Forbidden | InternalServer

type Query {
    "Fetch all users"
    getUsers: [User]
    """Fetch your own data only
    by authenticating with your username and password"""
    getUser (username: String!, password: String!): UserResult
 
    getUserOrPost(id: String!): UserOrPostRes

}

type Mutation {
    "Create a new user"
    createUser(form: UserInput!): UserResult
    "Update your details"
    updateUser(uid: String!, form: UserInput!): UserResult
    "Delete your account"
    deleteUser(uid: String!): UserResult
   
}